// commands/export.ts — `spawn export [name|id]`
//
// Captures a running claude spawn as a redistributable github repo. The
// output is the symmetric inverse of `--repo`: today `spawn claude hetzner
// --repo user/template` consumes a repo. After `spawn export`, the user
// gets a `spawn claude <cloud> --repo user/<slug>` line they can hand off
// or re-run.
//
// v1 scope: claude only. Mechanical capture (no agent introspection):
//   - ~/project/         (working tree, with aggressive .gitignore)
//   - ~/.claude/{skills,commands,hooks,CLAUDE.md,AGENTS.md,settings.json}
//     (settings.json is sanitized to strip likely tokens)
//   - generated spawn.md (frontmatter only — re-spawn metadata)
//   - generated README.md (re-spawn command + re-auth checklist for github)
//
// Followups (not in v1):
//   - claude reads its own session history to enumerate MCPs / OAuth
//     providers and writes them into spawn.md's setup steps
//   - local cloud target (currently routed through SshRunner like every
//     other cloud — works for SSH-backed clouds; local cloud uses a
//     trivial direct branch added below)

import type { SpawnRecord } from "../history.js";

import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import * as p from "@clack/prompts";
import { getErrorMessage } from "@openrouter/spawn-shared";
import pc from "picocolors";
import * as v from "valibot";
import { filterHistory } from "../history.js";
import { parseJsonWith } from "../shared/parse.js";
import { asyncTryCatch } from "../shared/result.js";
import { ensureSshKeys, getSshKeyOpts } from "../shared/ssh-keys.js";
import { makeSshRunner } from "../shared/ssh-runner.js";
import { shellQuote } from "../shared/ui.js";
import { buildRecordLabel, buildRecordSubtitle } from "./list.js";
import { handleCancel, isInteractiveTTY } from "./shared.js";

const CLAUDE_AGENT = "claude";
const REMOTE_RESULT_PATH = "/tmp/spawn-export-result.json";

const ResultSchema = v.object({
  slug: v.string(),
  url: v.string(),
});

const SLUG_PATTERN = /^[a-zA-Z0-9_.-]+\/[a-zA-Z0-9_.-]+$/;
const REPO_NAME_PATTERN = /^[a-zA-Z0-9_.-]+$/;

/** Find a claude spawn by name, id, or fall back to most-recent. */
function resolveTarget(target: string | undefined, records?: SpawnRecord[]): SpawnRecord | null {
  const all = records ?? filterHistory();
  const claudeRecords = all.filter((r) => r.agent === CLAUDE_AGENT);
  if (claudeRecords.length === 0) {
    return null;
  }
  if (!target) {
    return claudeRecords[0];
  }
  return (
    claudeRecords.find((r) => r.id === target || r.name === target || r.connection?.server_name === target) ?? null
  );
}

/** Sanitize a session name into a valid GitHub repo name. */
function sanitizeRepoName(input: string): string {
  const cleaned = input
    .toLowerCase()
    .replace(/[^a-z0-9_.-]+/g, "-")
    .replace(/^[-.]+|[-.]+$/g, "")
    .slice(0, 80);
  return cleaned || "spawn-export";
}

/** Build the spawn.md content from a record. Re-spawning consumes this. */
export function buildSpawnMd(record: SpawnRecord): string {
  const lines: string[] = [
    "---",
  ];
  if (record.name) {
    lines.push(`name: ${JSON.stringify(record.name)}`);
  }
  lines.push(`description: ${JSON.stringify(`Exported from spawn ${record.id}`)}`);
  lines.push("---");
  lines.push("");
  lines.push(`# ${record.name ?? "spawn export"}`);
  lines.push("");
  lines.push("This template was generated by `spawn export`. Re-spawn it with the");
  lines.push("command in the README.");
  lines.push("");
  return lines.join("\n");
}

/** Build the README. Renders as a re-auth checklist on github. */
export function buildReadme(record: SpawnRecord, slug: string): string {
  const cloud = record.cloud;
  const respawn = `spawn ${CLAUDE_AGENT} ${cloud} --repo ${slug}`;
  return [
    `# ${record.name ?? slug}`,
    "",
    `Exported from a [spawn](https://github.com/OpenRouterTeam/spawn) session on \`${cloud}\`.`,
    "",
    "## Quickstart",
    "",
    "```bash",
    respawn,
    "```",
    "",
    "## First-run checklist",
    "",
    "- [ ] `gh auth login` — re-auth GitHub on the new VM",
    "- [ ] Re-OAuth any MCP servers used in the original session (Spotify, Linear, etc.)",
    "- [ ] Run any project-specific install commands (e.g. `npm install`) in `project/`",
    "",
    "## What's in this repo",
    "",
    "- `project/` — the working tree at `~/project` from the source VM",
    "- `claude/` — sanitized agent config: skills, commands, hooks, CLAUDE.md, settings",
    "- `spawn.md` — machine-readable re-spawn metadata",
    "",
  ].join("\n");
}

/** Aggressive default .gitignore — better safe than committing secrets. */
export function buildGitignore(): string {
  return [
    "# spawn export defaults",
    "node_modules/",
    "dist/",
    "build/",
    ".next/",
    "target/",
    ".cache/",
    "coverage/",
    "*.log",
    ".env",
    ".env.*",
    "*.key",
    "*.pem",
    "id_rsa*",
    "id_ed25519*",
    ".DS_Store",
    "",
  ].join("\n");
}

/** Generate the bash script that runs on the VM. */
export function buildExportScript(opts: {
  spawnMd: string;
  readme: string;
  gitignore: string;
  slug: string;
  visibility: "private" | "public";
  resultPath: string;
}): string {
  const visibilityFlag = opts.visibility === "public" ? "--public" : "--private";
  return [
    "#!/bin/bash",
    "set -eo pipefail",
    "",
    'EXPORT_DIR="$(mktemp -d)"',
    'trap "rm -rf \\"$EXPORT_DIR\\"" EXIT',
    "",
    `cat > "$EXPORT_DIR/spawn.md" <<'SPAWN_MD_EOF'`,
    opts.spawnMd,
    "SPAWN_MD_EOF",
    "",
    `cat > "$EXPORT_DIR/README.md" <<'README_EOF'`,
    opts.readme,
    "README_EOF",
    "",
    `cat > "$EXPORT_DIR/.gitignore" <<'GITIGNORE_EOF'`,
    opts.gitignore,
    "GITIGNORE_EOF",
    "",
    "# Copy working tree if present",
    'if [ -d "$HOME/project" ]; then',
    '  mkdir -p "$EXPORT_DIR/project"',
    '  rsync -a --exclude=node_modules --exclude=.git --exclude=dist --exclude=.next --exclude=target --exclude=.env --exclude=".env.*" "$HOME/project/" "$EXPORT_DIR/project/"',
    "fi",
    "",
    "# Copy sanitized claude system dir",
    'mkdir -p "$EXPORT_DIR/claude"',
    "for d in skills commands hooks; do",
    '  if [ -d "$HOME/.claude/$d" ]; then',
    '    rsync -a "$HOME/.claude/$d/" "$EXPORT_DIR/claude/$d/"',
    "  fi",
    "done",
    "for f in CLAUDE.md AGENTS.md settings.json; do",
    '  if [ -f "$HOME/.claude/$f" ]; then',
    '    cp "$HOME/.claude/$f" "$EXPORT_DIR/claude/$f"',
    "  fi",
    "done",
    "",
    "# Strip likely-secret keys from settings.json (best effort).",
    "# Removes top-level fields whose name matches token/key/secret/password.",
    'if [ -f "$EXPORT_DIR/claude/settings.json" ] && command -v bun >/dev/null; then',
    '  _SETTINGS_PATH="$EXPORT_DIR/claude/settings.json" bun -e "',
    "    const path = process.env._SETTINGS_PATH;",
    "    const raw = await Bun.file(path).text();",
    "    let parsed; try { parsed = JSON.parse(raw); } catch { process.exit(0); }",
    "    if (parsed && typeof parsed === 'object') {",
    "      const denyRe = /(token|secret|password|api[_-]?key|auth)/i;",
    "      for (const k of Object.keys(parsed)) { if (denyRe.test(k)) delete parsed[k]; }",
    "      if (parsed.env && typeof parsed.env === 'object') {",
    "        for (const k of Object.keys(parsed.env)) { if (denyRe.test(k)) delete parsed.env[k]; }",
    "      }",
    "      await Bun.write(path, JSON.stringify(parsed, null, 2));",
    "    }",
    '  " || true',
    "fi",
    "",
    'cd "$EXPORT_DIR"',
    "git init -q -b main",
    "git add -A",
    'git -c user.email=spawn-export@openrouter.ai -c user.name="spawn export" commit -q -m "spawn export"',
    "",
    `gh repo create ${shellQuote(opts.slug)} ${visibilityFlag} --source=. --push --description=${shellQuote("Exported with spawn")}`,
    "",
    `printf '%s\\n' '{"slug":${JSON.stringify(opts.slug).replace(/'/g, "'\\''")},"url":"https://github.com/${opts.slug}"}' > ${shellQuote(opts.resultPath)}`,
    "",
  ].join("\n");
}

/** Prompt for slug + visibility. */
async function promptForRepo(record: SpawnRecord): Promise<{
  slug: string;
  visibility: "private" | "public";
} | null> {
  const defaultName = sanitizeRepoName(record.name ?? record.connection?.server_name ?? "spawn-export");
  const slug = await p.text({
    message: "GitHub repo to export to (user/repo)",
    placeholder: `your-username/${defaultName}`,
    validate: (value) => {
      if (!value) {
        return "Required. Format: user/repo";
      }
      if (!SLUG_PATTERN.test(value)) {
        return "Must be in user/repo format with only [a-zA-Z0-9_.-]";
      }
      const repoPart = value.split("/")[1];
      if (!REPO_NAME_PATTERN.test(repoPart)) {
        return "Repo name must contain only [a-zA-Z0-9_.-]";
      }
      return undefined;
    },
  });
  if (p.isCancel(slug)) {
    return null;
  }

  const visibility = await p.select({
    message: "Visibility",
    options: [
      {
        value: "private",
        label: "Private",
        hint: "default",
      },
      {
        value: "public",
        label: "Public",
      },
    ],
    initialValue: "private",
  });
  if (p.isCancel(visibility)) {
    return null;
  }

  return {
    slug,
    visibility: visibility === "public" ? "public" : "private",
  };
}

/** Options for cmdExport — injectable for testing. */
export interface ExportOptions {
  /** Override the runner construction (test injection). */
  makeRunner?: (
    ip: string,
    user: string,
    keyOpts: string[],
  ) => {
    runServer: (cmd: string, timeoutSecs?: number) => Promise<void>;
    downloadFile: (remotePath: string, localPath: string) => Promise<void>;
    uploadFile: (localPath: string, remotePath: string) => Promise<void>;
  };
  /** Skip interactive prompts; supply repo info directly. */
  repo?: {
    slug: string;
    visibility: "private" | "public";
  };
  /** Inject the candidate records directly (test seam to skip filterHistory). */
  records?: SpawnRecord[];
}

/** Top-level command: `spawn export [target]`. */
export async function cmdExport(target: string | undefined, options?: ExportOptions): Promise<void> {
  const record = resolveTarget(target, options?.records);
  if (!record) {
    if (target) {
      p.log.error(`No claude spawn matches ${pc.bold(target)}.`);
      p.log.info(`Run ${pc.cyan("spawn list -a claude")} to see available targets.`);
    } else {
      p.log.info("No claude spawns recorded yet.");
      p.log.info(`Run ${pc.cyan("spawn claude <cloud>")} first, then export the result.`);
    }
    process.exit(1);
  }

  if (record.agent !== CLAUDE_AGENT) {
    p.log.error(`spawn export currently supports claude only (got ${pc.bold(record.agent)}).`);
    p.log.info("Other agents will be added once their config introspection lands.");
    process.exit(1);
  }

  const conn = record.connection;
  if (!conn) {
    p.log.error("Cannot export: spawn has no connection information.");
    process.exit(1);
  }
  if (conn.deleted) {
    p.log.error("Cannot export: server has been deleted.");
    process.exit(1);
  }
  if (conn.ip === "sprite-console") {
    p.log.error("Cannot export: Sprite-console connections aren't SSH-accessible.");
    p.log.info("SSH directly into the VM and run `gh repo create` manually.");
    process.exit(1);
  }

  p.log.step(`Exporting ${pc.bold(buildRecordLabel(record))} ${pc.dim(`(${buildRecordSubtitle(record, null)})`)}`);

  // Resolve repo target
  let repo = options?.repo;
  if (!repo) {
    if (!isInteractiveTTY()) {
      p.log.error("spawn export requires --repo <slug> in non-interactive mode (not yet supported).");
      process.exit(1);
    }
    const prompted = await promptForRepo(record);
    if (!prompted) {
      handleCancel();
    }
    repo = prompted!;
  }

  // Build content
  const spawnMd = buildSpawnMd(record);
  const readme = buildReadme(record, repo.slug);
  const gitignore = buildGitignore();
  const script = buildExportScript({
    spawnMd,
    readme,
    gitignore,
    slug: repo.slug,
    visibility: repo.visibility,
    resultPath: REMOTE_RESULT_PATH,
  });

  // SSH runner
  const keyOpts = options?.makeRunner ? [] : getSshKeyOpts(await ensureSshKeys());
  const runner = options?.makeRunner
    ? options.makeRunner(conn.ip, conn.user, keyOpts)
    : makeSshRunner(conn.ip, conn.user, keyOpts);

  // Run the export script. 10-min timeout — large repos take time to push.
  p.log.step("Running export on the VM...");
  const runResult = await asyncTryCatch(() => runner.runServer(script, 600));
  if (!runResult.ok) {
    p.log.error(`Export failed: ${getErrorMessage(runResult.error)}`);
    p.log.info("Check that `gh` is authenticated on the VM (`gh auth status`).");
    process.exit(1);
  }

  // Download result file
  const localTmp = mkdtempSync(join(tmpdir(), "spawn-export-"));
  const localResult = join(localTmp, "result.json");
  const dlResult = await asyncTryCatch(() => runner.downloadFile(REMOTE_RESULT_PATH, localResult));
  if (!dlResult.ok) {
    rmSync(localTmp, {
      recursive: true,
      force: true,
    });
    p.log.error(`Could not read export result: ${getErrorMessage(dlResult.error)}`);
    process.exit(1);
  }
  const text = readFileSync(localResult, "utf8");
  rmSync(localTmp, {
    recursive: true,
    force: true,
  });
  const parsed = parseJsonWith(text, ResultSchema);
  if (!parsed) {
    p.log.error("Export ran but produced no parseable result.");
    process.exit(1);
  }
  console.log();
  p.log.success(`Exported to ${pc.cyan(parsed.url)}`);
  console.log();
  console.log(pc.dim("Re-spawn with:"));
  console.log(`  ${pc.cyan(`spawn ${CLAUDE_AGENT} ${record.cloud} --repo ${parsed.slug}`)}`);
  console.log();
}
