name: Agent Request
description: Request a new AI agent
title: "[Agent]: "
labels: ["agent-request", "enhancement", "pending-review"]
body:
  - type: input
    id: agent-url
    attributes:
      label: Link
      placeholder: https://github.com/org/agent
    validations:
      required: false

  - type: textarea
    id: why
    attributes:
      label: Why?
      placeholder: "What makes this agent worth adding?"
    validations:
      required: false
