name: Bug Report
description: Something broken?
title: "[Bug]: "
labels: ["bug", "pending-review"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: "Paste the error or describe what went wrong"
      render: shell
    validations:
      required: true
