name: Bug Report
description: Report an error or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please paste the full error log or run output below.

  - type: textarea
    id: error-log
    attributes:
      label: Error Log / Run Output
      description: Paste the complete terminal output showing the error
      placeholder: |
        $ spawn claude sprite
        [error output here...]
      render: shell
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected the agent to launch successfully
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Run these commands and paste the output:
        - spawn version
        - uname -a
      placeholder: |
        spawn v1.0.0
        Darwin 23.1.0
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other details that might help
      placeholder: This only happens when using --prompt flag
    validations:
      required: false
