name: CLI Feature Request
description: Suggest something for the spawn CLI
title: "[CLI]: "
labels: ["cli", "enhancement", "pending-review"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      placeholder: "e.g. Add a --dry-run flag to preview what gets created"
    validations:
      required: true
