name: Cloud Provider Request
description: Request a new cloud provider
title: "[Cloud]: "
labels: ["cloud-request", "enhancement", "pending-review"]
body:
  - type: input
    id: cloud-url
    attributes:
      label: Link
      placeholder: https://cloud.provider.com
    validations:
      required: false

  - type: textarea
    id: why
    attributes:
      label: Why?
      placeholder: "What makes this provider a good fit? (pricing, speed, etc.)"
    validations:
      required: false
